[project]
name = "hacktx-25"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.119.0",
    "numpy>=2.3.4",
    "union>=0.1.194",
]
